name: Build APK
run-name: Build stupid fluffychat
on: [push]
# on:
#   release:
#     types:
#       - created
concurrency:
  group: release_workflow
  cancel-in-progress: true

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: flutter pub get
      - name: Prepare Android Release Build
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
        run: ./scripts/prepare-android-release.sh
      - run: flutter build apk --release
      - name: Upload build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/app/outputs/apk/release/app-release.apk
          asset_name: fluffychat.apk
          asset_content_type: application/vnd.android.package-archive

